from pathlib import Path

src_path = Path('tools/generate_paps_verbal_10_packages.py')
src = src_path.read_text(encoding='utf-8')
needle = "# Ensure every adapted passage is genuinely long enough."
if needle not in src:
    raise RuntimeError('Generator marker not found')

supplements = {
    'Perubahan Iklim dan Hujan Ekstrem': "Data iklim juga perlu dikomunikasikan dengan cara yang mudah dipahami. Peringatan yang terlalu teknis dapat gagal mendorong tindakan, sedangkan informasi yang jelas membantu masyarakat menilai risiko. Pemerintah, peneliti, dan warga karena itu perlu membangun kebiasaan membaca informasi cuaca dan iklim secara berkala. Dengan pemahaman yang lebih baik, keputusan tentang tata ruang, pertanian, kesiapsiagaan, dan penggunaan sumber daya dapat disesuaikan sebelum dampak ekstrem menjadi lebih besar.",
    'Transportasi Publik dan Udara Perkotaan': "Perubahan kebiasaan perjalanan juga memerlukan waktu. Kebijakan yang baik perlu dievaluasi melalui data jumlah penumpang, waktu perjalanan, keterjangkauan tarif, dan kualitas layanan. Jika hambatan perjalanan dapat dikurangi secara bertahap, masyarakat memiliki alasan yang lebih kuat untuk meninggalkan kendaraan pribadi pada sebagian perjalanan harian. Dengan demikian, perbaikan transportasi tidak hanya menyangkut teknologi, tetapi juga pengalaman pengguna.",
    'Ekonomi Sirkular': "Perubahan menuju pola sirkular juga membutuhkan informasi yang mudah dipahami masyarakat. Label mengenai daya tahan, ketersediaan suku cadang, atau cara mengembalikan produk dapat membantu konsumen mengambil keputusan. Di tingkat perusahaan, pencatatan aliran material penting untuk mengetahui bagian mana yang paling banyak menghasilkan pemborosan. Dengan data tersebut, intervensi dapat diarahkan pada titik yang memberi dampak terbesar.",
    'Panas Bumi Indonesia': "Keberhasilan proyek juga dipengaruhi oleh waktu. Eksplorasi dan pembangunan fasilitas dapat berlangsung bertahun-tahun, sehingga kepastian kebijakan penting bagi investor dan masyarakat. Di saat yang sama, proses yang panjang memberi kesempatan untuk memperbaiki kajian dan konsultasi. Tantangannya adalah menjaga agar percepatan tidak berubah menjadi pengabaian prosedur, tetapi prosedur juga tidak membuat potensi energi berhenti tanpa keputusan.",
    'Pembatasan Gawai di Sekolah': "Sekolah juga perlu mengevaluasi kebijakan secara berkala. Aturan yang cocok untuk satu jenjang belum tentu tepat untuk jenjang lain. Guru dapat mengamati perubahan konsentrasi, interaksi sosial, dan efektivitas tugas digital. Jika ditemukan masalah, mekanisme penggunaan dapat diperbaiki tanpa harus memilih antara kebebasan penuh dan larangan total. Pendekatan seperti ini membuat aturan lebih responsif terhadap kebutuhan belajar nyata.",
    'Ketimpangan Kesehatan': "Data yang baik pada akhirnya harus diikuti tindakan. Mengetahui adanya kesenjangan tidak otomatis menguranginya. Temuan perlu diterjemahkan menjadi prioritas program, pembiayaan, peningkatan layanan, dan evaluasi yang berulang. Jika data terus diperbarui, pemerintah dapat melihat apakah intervensi benar-benar membantu kelompok yang sebelumnya tertinggal atau justru menciptakan kesenjangan baru yang perlu ditangani.",
    'Batik sebagai Warisan Budaya': "Peran konsumen juga penting dalam menjaga keberlanjutan batik. Ketika pembeli memahami perbedaan teknik, proses, dan nilai di balik sebuah karya, keputusan membeli dapat ikut mendukung pengrajin dan pewarisan keterampilan. Pendidikan budaya karena itu tidak hanya ditujukan kepada calon pembatik, tetapi juga kepada masyarakat sebagai pengguna. Apresiasi yang lebih baik dapat membantu tradisi tetap memiliki ruang dalam kehidupan modern.",
    'Budaya Jamu': "Pelestarian juga berkaitan dengan keberlanjutan bahan. Tanaman yang digunakan sebagai bahan jamu perlu dibudidayakan secara bertanggung jawab agar ketersediaannya terjaga. Dokumentasi pengetahuan dapat membantu proses belajar, tetapi dokumentasi tidak sepenuhnya menggantikan praktik langsung. Banyak keterampilan meracik berkembang melalui pengalaman, pengamatan, dan interaksi dengan pelaku lain. Karena itu, pelestarian perlu menjaga manusia sekaligus sumber daya alamnya.",
    'Keamanan Anak di Ruang Digital': "Anak juga perlu diberi ruang untuk berpartisipasi dalam penyusunan pendekatan keamanan digital. Mereka memahami jenis platform, bahasa, dan situasi yang sering muncul dalam pergaulan daring. Dengan melibatkan anak, pesan keselamatan dapat menjadi lebih relevan dan tidak terdengar sekadar menggurui. Partisipasi tersebut tetap perlu didampingi orang dewasa dan ditempatkan dalam kerangka perlindungan yang jelas.",
    'Kesenjangan Pembelajaran Digital': "Evaluasi pembelajaran digital juga perlu melihat pengalaman siswa dan guru, bukan hanya data penggunaan platform. Banyaknya akun aktif belum tentu menunjukkan pemahaman yang lebih baik. Wawancara, hasil belajar, dan pengamatan proses dapat memberi gambaran lebih lengkap. Dengan cara itu, sekolah dapat membedakan teknologi yang benar-benar membantu pembelajaran dari teknologi yang hanya menambah beban administratif atau biaya tanpa manfaat sepadan."
}

insert = "\n# Add source-consistent supplements before validating passage length.\nSUPPLEMENTS = " + repr(supplements) + "\nfor _p in PASSAGES:\n    _p['body'] += '\\n\\n' + SUPPLEMENTS[_p['title']]\n\n"
src = src.replace(needle, insert + needle, 1)
exec(compile(src, str(src_path), 'exec'), {'__name__': '__main__', '__file__': str(src_path)})
